### ISSUE TITLE
Error : IDA 7.0 cannot save 

### ISSUE THREAD

**Issue by kuqadk3** [andreafioraldi/IDAngr#12]
When i trying to save all my constrains in AngrIDA, got this problem

> Traceback (most recent call last):
  File "C:/Program Files/IDA 7.0/plugins\idangr\main_gui.py", line 649, in save_clicked
    save_ctx(filename)
  File "C:/Program Files/IDA 7.0/plugins\idangr\main_gui.py", line 47, in save_ctx
    pickle.dump(_idangr_ctx, fh)
  File "C:\python27-x64\Lib\pickle.py", line 1376, in dump
    Pickler(file, protocol).dump(obj)
  File "C:\python27-x64\Lib\pickle.py", line 224, in dump
    self.save(obj)
  File "C:\python27-x64\Lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\python27-x64\Lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\python27-x64\Lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\python27-x64\Lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\python27-x64\Lib\pickle.py", line 669, in _batch_setitems
    save(v)
  File "C:\python27-x64\Lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\python27-x64\Lib\pickle.py", line 401, in save_reduce
    save(args)
  File "C:\python27-x64\Lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\python27-x64\Lib\pickle.py", line 568, in save_tuple
    save(element)
  File "C:\python27-x64\Lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\python27-x64\Lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\python27-x64\Lib\pickle.py", line 669, in _batch_setitems
    save(v)
  File "C:\python27-x64\Lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\python27-x64\Lib\pickle.py", line 422, in save_reduce
    self._batch_setitems(dictitems)
  File "C:\python27-x64\Lib\pickle.py", line 669, in _batch_setitems
    save(v)
  File "C:\python27-x64\Lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\python27-x64\Lib\pickle.py", line 606, in save_list
    self._batch_appends(iter(obj))
  File "C:\python27-x64\Lib\pickle.py", line 621, in _batch_appends
    save(x)
  File "C:\python27-x64\Lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\python27-x64\Lib\pickle.py", line 401, in save_reduce
    save(args)
  File "C:\python27-x64\Lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\python27-x64\Lib\pickle.py", line 568, in save_tuple
    save(element)
  File "C:\python27-x64\Lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\python27-x64\Lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\python27-x64\Lib\pickle.py", line 669, in _batch_setitems
    save(v)
  File "C:\python27-x64\Lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\python27-x64\Lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\python27-x64\Lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\python27-x64\Lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\python27-x64\Lib\pickle.py", line 669, in _batch_setitems
    save(v)
  File "C:\python27-x64\Lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\python27-x64\Lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\python27-x64\Lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\python27-x64\Lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\python27-x64\Lib\pickle.py", line 669, in _batch_setitems
    save(v)
  File "C:\python27-x64\Lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\python27-x64\Lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\python27-x64\Lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\python27-x64\Lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\python27-x64\Lib\pickle.py", line 669, in _batch_setitems
    save(v)
  File "C:\python27-x64\Lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\python27-x64\Lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\python27-x64\Lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\python27-x64\Lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\python27-x64\Lib\pickle.py", line 669, in _batch_setitems
    save(v)
  File "C:\python27-x64\Lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\python27-x64\Lib\pickle.py", line 606, in save_list
    self._batch_appends(iter(obj))
  File "C:\python27-x64\Lib\pickle.py", line 621, in _batch_appends
    save(x)
  File "C:\python27-x64\Lib\pickle.py", line 306, in save
    rv = reduce(self.proto)
  File "C:\python27-x64\Lib\copy_reg.py", line 84, in _reduce_ex
    dict = getstate()
  File "C:\python27-x64\lib\site-packages\cle\backends\elf\elf.py", line 386, in __getstate__
    raise ValueError("Can't pickle an object loaded from a stream")
ValueError: Can't pickle an object loaded from a stream

**Comment by andreafioraldi** [comment]
*IDAngr

I will remove this ASAP, saving the state to a file was supported only in the first versions and probably the lastest angr 7 changes have broken the code.
Use a script if u want to do complex stuffs from the debugger state.
