### ISSUE TITLE
object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by M0dRat** [andreafioraldi/IDAngr#9]
I used version Ida angr, and a set of required packages (https://github.com/andreafioraldi/angr-win64-wheels) of 22 may, and have never experienced any problems. Today, 07.20 I updated both a set of packages and ida angr then I had such problem:.
![screenshot 137](https://user-images.githubusercontent.com/39669467/43025240-9818067c-8c79-11e8-866b-e987d2abaad8.png)

 If I try to use an old version (may 22) of IDA angr with new pre-compiled packages I get this error: 

> Traceback (most recent call last):
  File "C:/Program Files/IDA 7.0/MyScripts/IDAngr\idangr\gui.py", line 405, in runClicked
    sm.explore(find=conds[0], avoid=conds[1])
  File "C:\Python27\lib\site-packages\angr\misc\immutability.py", line 24, in _wrapper
    if method(self, *args, **kwargs) is not self:
  File "C:\Python27\lib\site-packages\angr\sim_manager.py", line 238, in explore
    self.run(stash=stash, n=n, **kwargs)
  File "C:\Python27\lib\site-packages\angr\misc\immutability.py", line 24, in _wrapper
    if method(self, *args, **kwargs) is not self:
  File "C:\Python27\lib\site-packages\angr\sim_manager.py", line 260, in run
    self.step(stash=stash, **kwargs)
  File "C:\Python27\lib\site-packages\angr\misc\hookset.py", line 57, in __call__
    result = next_hook(self.func.im_self, *args, **kwargs)
  File "C:\Python27\lib\site-packages\angr\exploration_techniques\explorer.py", line 101, in step
    return simgr.step(stash=stash, extra_stop_points=base_extra_stop_points | self._extra_stop_points, **kwargs)
  File "C:\Python27\lib\site-packages\angr\misc\hookset.py", line 60, in __call__
    result = self.func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\angr\misc\immutability.py", line 24, in _wrapper
    if method(self, *args, **kwargs) is not self:
  File "C:\Python27\lib\site-packages\angr\sim_manager.py", line 341, in step
    successors = self.step_state(state, successor_func, **run_args)
  File "C:\Python27\lib\site-packages\angr\sim_manager.py", line 362, in step_state
    successors = self.successors(state, successor_func, **run_args)
  File "C:\Python27\lib\site-packages\angr\sim_manager.py", line 401, in successors
    return self._project.factory.successors(state, **run_args)
  File "C:\Python27\lib\site-packages\angr\factory.py", line 61, in successors
    return self.project.engines.successors(*args, **kwargs)
  File "C:\Python27\lib\site-packages\angr\engines\hub.py", line 128, in successors
    r = engine.process(state, **kwargs)
  File "C:\Python27\lib\site-packages\angr\engines\vex\engine.py", line 135, in process
    opt_level=opt_level)
  File "C:\Python27\lib\site-packages\angr\engines\engine.py", line 35, in process
    new_state = state.copy()
  File "C:\Python27\lib\site-packages\angr\sim_state.py", line 440, in copy
    c_plugins = self._copy_plugins()
  File "C:\Python27\lib\site-packages\angr\sim_state.py", line 427, in _copy_plugins
    out[n] = p.copy(memo)
TypeError: copy() takes exactly 1 argument (2 given)

Is there anything you can do about it? Or how I can roll back the version. The only problem is that I could not find the old versions of the compiled packages (https://github.com/andreafioraldi/angr-win64-wheels) under windows... 
P.S. Im using IDA Version 7.0.170914 under Windows 10 x64

**Comment by andreafioraldi** [comment]
Hi @M0dRat 
This is an issue of the windows simos in angr. I fixed it some days ago with a pull request to angr but i haven't compiled the wheels yet.
You should compile it yourself or wait a day.
